### ISSUE TITLE
Fail to install

### ISSUE THREAD

**Issue by Free16t** [willzeng/WikiNets#128]
Hi,

I'm currently trying to install WikiNets on my server (FreeBSD 9.2) but when I try to install it I fail.

```
/usr/WikiNets-master # ls
.gitmodules             cypherQueryExample.txt  server.sh
LICENSE.txt             node_modules            static
Procfile                old                     web.js
README.md               package.json            wikinets.coffee
THANKS.md               public

/usr/WikiNets-master # npm install
npm WARN package.json node-example@0.0.1 No repository field.

/usr/WikiNets-master # sh server.sh
server.sh: coffee: not found
server.sh: coffee: not found
GET http://wikinets-edge:wiKnj2gYeYOlzWPUcKYb@wikinetsedge.sb01.stations.graphenedb.com:24789

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:901:11)
    at HTTPServer.Server._listen2 (net.js:1039:14)
    at listen (net.js:1061:10)
    at HTTPServer.Server.listen (net.js:1135:5)
    at new MyApp (/usr/WikiNets-master/wikinets.coffee:563:11)
    at Object.<anonymous> (/usr/WikiNets-master/web.js:21:7)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

What should I do ?
Thanks a lot

A.H

**Comment by willzeng** [comment]
It seems coffeescript is not installing well via npm.  Try to run this line first in the directory that contains WikiNets
`sudo npm install -g coffee-script`

**Comment by Free16t** [comment]
Thanks, it's better. But I still have an error : 

```
sh server.sh
18:04:28 - compiled /usr/WikiNets-master/static/main.coffee
GET http://wikinets-edge:wiKnj2gYeYOlzWPUcKYb@wikinetsedge.sb01.stations.graphenedb.com:24789 

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:901:11)
    at HTTPServer.Server._listen2 (net.js:1039:14)
    at listen (net.js:1061:10)
    at HTTPServer.Server.listen (net.js:1135:5)
    at new MyApp (/usr/WikiNets-master/wikinets.coffee:563:11)
    at Object.<anonymous> (/usr/WikiNets-master/web.js:21:7)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
root@root:/usr/WikiNets-master # /usr/WikiNets-master/static/core-coffee/MiniMap.coffee:122:1: error: unexpected indentation
            ### should eventually implement directed arrows here ###
^^^^^^^^^^^^
18:04:32 - compiled /usr/WikiNets-master/static/core-coffee/DataController.coffee
18:04:32 - compiled /usr/WikiNets-master/static/core-coffee/ForceSliders.coffee
18:04:32 - compiled /usr/WikiNets-master/static/core-coffee/GraphModel.coffee
18:04:32 - compiled /usr/WikiNets-master/static/core-coffee/GraphView.coffee
18:04:32 - compiled /usr/WikiNets-master/static/core-coffee/KeyListener.coffee
18:04:32 - compiled /usr/WikiNets-master/static/core-coffee/Layout.coffee
18:04:32 - compiled /usr/WikiNets-master/static/core-coffee/LinkDistribution.coffee
18:04:32 - compiled /usr/WikiNets-master/static/core-coffee/LinkEdit.coffee
18:04:32 - compiled /usr/WikiNets-master/static/core-coffee/LinkHover.coffee
18:04:32 - compiled /usr/WikiNets-master/static/core-coffee/LinkSelection.coffee
18:04:32 - compiled /usr/WikiNets-master/static/core-coffee/ListView.coffee
18:04:32 - compiled /usr/WikiNets-master/static/core-coffee/Neo4jDataController.coffee
18:04:32 - compiled /usr/WikiNets-master/static/core-coffee/NodeCreationPopout.coffee
18:04:32 - compiled /usr/WikiNets-master/static/core-coffee/NodeDetails.coffee
18:04:32 - compiled /usr/WikiNets-master/static/core-coffee/NodeEdit.coffee
18:04:32 - compiled /usr/WikiNets-master/static/core-coffee/NodeSearch.coffee
18:04:32 - compiled /usr/WikiNets-master/static/core-coffee/NodeSelection.coffee
18:04:32 - compiled /usr/WikiNets-master/static/core-coffee/OverlayCreate.coffee
18:04:32 - compiled /usr/WikiNets-master/static/core-coffee/SelectionLayer.coffee
18:04:32 - compiled /usr/WikiNets-master/static/core-coffee/ShowAll.coffee
18:04:32 - compiled /usr/WikiNets-master/static/core-coffee/SimpleSearchBox.coffee
18:04:32 - compiled /usr/WikiNets-master/static/core-coffee/Sliders.coffee
18:04:32 - compiled /usr/WikiNets-master/static/core-coffee/Stats.coffee
18:04:32 - compiled /usr/WikiNets-master/static/core-coffee/SyntaxCreate.coffee
18:04:32 - compiled /usr/WikiNets-master/static/core-coffee/ToolBox.coffee
18:04:32 - compiled /usr/WikiNets-master/static/core-coffee/TopBarCreate.coffee
18:04:32 - compiled /usr/WikiNets-master/static/core-coffee/VisualSearch.coffee
18:04:32 - compiled /usr/WikiNets-master/static/core-coffee/WikiNetsDataProvider.coffee
18:04:32 - compiled /usr/WikiNets-master/static/core-coffee/Celestrium.coffee
18:04:32 - compiled /usr/WikiNets-master/static/core-coffee/Create.coffee
18:04:32 - compiled /usr/WikiNets-master/static/core-coffee/Expander.coffee
18:04:32 - compiled /usr/WikiNets-master/static/core-coffee/DataProvider.coffee
```

Sincerely
